<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class BotsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('bots')->delete();
        
        \DB::table('bots')->insert(array (
            0 => 
            array (
                'id' => 1,
                'telegram_owner_chat_id' => NULL,
                'telegram_bot_name' => NULL,
                'telegram_bot_token' => NULL,
                'telegram_get_me_api_response' => NULL,
                'telegram_bot_status' => 'DeActive',
                'telegram_webhook_is_set' => 1,
                'bale_owner_chat_id' => 485750575,
                'bale_bot_name' => 'taba_bot',
                'bale_bot_token' => '72780264:XPt2lbs1ywsLWLCJ4utPZehbODQLTHbUstxpFXaD',
                'bale_get_me_api_response' => '{"id":72780264,"first_name":"taba_bot","username":"taba_bot","is_bot":true}',
                'bale_bot_status' => 'Active',
                'bale_webhook_is_set' => 0,
                'block_strategy' => 'block_first',
                'supported_message_types' => 'text',
                'supported_message_template' => 'https://',
                'created_at' => '2023-04-03 13:18:44',
                'updated_at' => '2023-04-03 13:18:45',
                'bot_mother_id' => NULL,
                'endpoint_id' => NULL,
                'language_code' => NULL,
                'type' => NULL,
            ),
            1 => 
            array (
                'id' => 6,
                'telegram_owner_chat_id' => 151370482,
                'telegram_bot_name' => 'test_group2_bot',
                'telegram_bot_token' => '6008826425:AAHDBct4iW6Gsxm6G_96j2zvhxu2_JGwc9I',
                'telegram_get_me_api_response' => '{"id":6008826425,"is_bot":true,"first_name":"test_group_bot","username":"test_group2_bot","can_join_groups":true,"can_read_all_group_messages":false,"supports_inline_queries":false}',
                'telegram_bot_status' => 'Active',
                'telegram_webhook_is_set' => 1,
                'bale_owner_chat_id' => NULL,
                'bale_bot_name' => NULL,
                'bale_bot_token' => NULL,
                'bale_get_me_api_response' => NULL,
                'bale_bot_status' => 'DeActive',
                'bale_webhook_is_set' => 0,
                'block_strategy' => 'block_first',
                'supported_message_types' => 'text',
                'supported_message_template' => 'https://',
                'created_at' => '2023-04-18 13:53:42',
                'updated_at' => '2023-04-18 13:53:42',
                'bot_mother_id' => 1,
                'endpoint_id' => NULL,
                'language_code' => NULL,
                'type' => NULL,
            ),
            2 => 
            array (
                'id' => 7,
                'telegram_owner_chat_id' => NULL,
                'telegram_bot_name' => NULL,
                'telegram_bot_token' => NULL,
                'telegram_get_me_api_response' => NULL,
                'telegram_bot_status' => 'DeActive',
                'telegram_webhook_is_set' => 0,
                'bale_owner_chat_id' => 485750575,
                'bale_bot_name' => 'TestGroupbot',
                'bale_bot_token' => '1140668579:5XLYvriWQ1vwNJaKjHKTRUik7lE8Fl2vs92sB47V',
                'bale_get_me_api_response' => '{"id":1140668579,"first_name":"TestGroupbot","username":"TestGroupbot","is_bot":true}',
                'bale_bot_status' => 'Active',
                'bale_webhook_is_set' => 1,
                'block_strategy' => 'block_first',
                'supported_message_types' => 'text',
                'supported_message_template' => 'https://',
                'created_at' => '2023-04-18 13:54:39',
                'updated_at' => '2023-04-18 13:54:39',
                'bot_mother_id' => 1,
                'endpoint_id' => NULL,
                'language_code' => NULL,
                'type' => NULL,
            ),
            3 => 
            array (
                'id' => 8,
                'telegram_owner_chat_id' => 6877922777,
                'telegram_bot_name' => 'mission_islam_bot',
                'telegram_bot_token' => '8434130485:AAHK658pA-G_UUPqVKghKmEYiDRoElaVFDE',
                'telegram_get_me_api_response' => '{"id":8434130485,"is_bot":true,"first_name":"\\u0631\\u0648\\u0628\\u0627\\u062a \\u0645\\u0627\\u0645\\u0648\\u0631\\u06cc\\u062a \\u062a\\u0628\\u0644\\u06cc\\u063a \\u0627\\u0633\\u0644\\u0627\\u0645 \\u06f1\\u06f4\\u06f0 \\u0632\\u0628\\u0627\\u0646","username":"mission_islam_bot","can_join_groups":true,"can_read_all_group_messages":false,"supports_inline_queries":false,"can_connect_to_business":false,"has_main_web_app":false}',
                'telegram_bot_status' => 'Active',
                'telegram_webhook_is_set' => 1,
                'bale_owner_chat_id' => NULL,
                'bale_bot_name' => NULL,
                'bale_bot_token' => NULL,
                'bale_get_me_api_response' => NULL,
                'bale_bot_status' => 'DeActive',
                'bale_webhook_is_set' => 0,
                'block_strategy' => 'block_first',
                'supported_message_types' => 'text',
                'supported_message_template' => 'https://',
                'created_at' => '2025-12-25 09:49:06',
                'updated_at' => '2026-01-03 15:53:42',
                'bot_mother_id' => 1,
                'endpoint_id' => 'webhook-mission-bot',
                'language_code' => 'fa',
                'type' => 'telegram',
            ),
            4 => 
            array (
                'id' => 9,
                'telegram_owner_chat_id' => 6877922777,
                'telegram_bot_name' => 'task_approver_bot',
                'telegram_bot_token' => '8427690895:AAH7UJAzE8bzg7nFuqs0Ci16n13SZRhJ5Xc',
                'telegram_get_me_api_response' => '{"id":8427690895,"is_bot":true,"first_name":"\\u062a\\u0627\\u06cc\\u06cc\\u062f \\u0648\\u0638\\u0627\\u06cc\\u0641 \\u062a\\u0628\\u0644\\u06cc\\u063a \\u0627\\u0633\\u0644\\u0627\\u0645","username":"task_approver_bot","can_join_groups":true,"can_read_all_group_messages":false,"supports_inline_queries":false,"can_connect_to_business":false,"has_main_web_app":false,"has_topics_enabled":false}',
                'telegram_bot_status' => 'Active',
                'telegram_webhook_is_set' => 1,
                'bale_owner_chat_id' => NULL,
                'bale_bot_name' => NULL,
                'bale_bot_token' => NULL,
                'bale_get_me_api_response' => NULL,
                'bale_bot_status' => 'DeActive',
                'bale_webhook_is_set' => 0,
                'block_strategy' => 'block_first',
                'supported_message_types' => 'text',
                'supported_message_template' => 'https://',
                'created_at' => '2025-12-25 09:51:04',
                'updated_at' => '2026-01-03 15:53:05',
                'bot_mother_id' => 1,
                'endpoint_id' => 'webhook-task-approval',
                'language_code' => 'fa',
                'type' => 'telegram',
            ),
            5 => 
            array (
                'id' => 10,
                'telegram_owner_chat_id' => NULL,
                'telegram_bot_name' => NULL,
                'telegram_bot_token' => NULL,
                'telegram_get_me_api_response' => NULL,
                'telegram_bot_status' => 'DeActive',
                'telegram_webhook_is_set' => 0,
                'bale_owner_chat_id' => 6877922777,
                'bale_bot_name' => 'islamvoice_reg_user_bot',
                'bale_bot_token' => '2141755763:Kvzc1ia9lSYXd5mhVYn8rwuz_Jjscch9jcc',
                'bale_get_me_api_response' => '{"id":2141755763,"is_bot":true,"first_name":"islamvoice_reg_user_bot","last_name":"","username":"islamvoice_reg_user_bot"}',
                'bale_bot_status' => 'Active',
                'bale_webhook_is_set' => 1,
                'block_strategy' => 'block_first',
                'supported_message_types' => 'text',
                'supported_message_template' => 'https://',
                'created_at' => '2025-12-25 10:14:16',
                'updated_at' => '2026-01-03 15:51:58',
                'bot_mother_id' => 1,
                'endpoint_id' => 'webhook-personnel-registration',
                'language_code' => 'fa',
                'type' => 'bale',
            ),
            6 => 
            array (
                'id' => 11,
                'telegram_owner_chat_id' => NULL,
                'telegram_bot_name' => NULL,
                'telegram_bot_token' => NULL,
                'telegram_get_me_api_response' => NULL,
                'telegram_bot_status' => 'DeActive',
                'telegram_webhook_is_set' => 0,
                'bale_owner_chat_id' => 6877922777,
                'bale_bot_name' => 'islam_voice_mission_bot',
                'bale_bot_token' => '1285339896:FPtxIxbYBM5Qhjv0E-PUSbtlr5iGO42vBk4',
                'bale_get_me_api_response' => '{"id":1285339896,"is_bot":true,"first_name":"islam_voice_mission_bot","last_name":"","username":"islam_voice_mission_bot"}',
                'bale_bot_status' => 'Active',
                'bale_webhook_is_set' => 1,
                'block_strategy' => 'block_first',
                'supported_message_types' => 'text',
                'supported_message_template' => 'https://',
                'created_at' => '2025-12-25 10:22:14',
                'updated_at' => '2026-01-03 15:50:38',
                'bot_mother_id' => 1,
                'endpoint_id' => 'webhook-mission-bot',
                'language_code' => 'fa',
                'type' => 'bale',
            ),
            7 => 
            array (
                'id' => 12,
                'telegram_owner_chat_id' => 6877922777,
                'telegram_bot_name' => 'islamvoice_admin_bot',
                'telegram_bot_token' => '8513970457:AAF-BfeLZyK1mhdT0pcohk73JTcm5MKK7fA',
                'telegram_get_me_api_response' => '{"id":8513970457,"is_bot":true,"first_name":"\\u0627\\u062f\\u0645\\u06cc\\u0646 \\u062a\\u0646\\u0646\\u062a \\u0631\\u0648\\u0628\\u0627\\u062a \\u062a\\u0628\\u0644\\u06cc\\u063a","username":"islamvoice_admin_bot","can_join_groups":true,"can_read_all_group_messages":false,"supports_inline_queries":false,"can_connect_to_business":false,"has_main_web_app":false,"has_topics_enabled":false}',
                'telegram_bot_status' => 'Active',
                'telegram_webhook_is_set' => 1,
                'bale_owner_chat_id' => NULL,
                'bale_bot_name' => NULL,
                'bale_bot_token' => NULL,
                'bale_get_me_api_response' => NULL,
                'bale_bot_status' => 'DeActive',
                'bale_webhook_is_set' => 0,
                'block_strategy' => 'block_first',
                'supported_message_types' => 'text',
                'supported_message_template' => 'https://',
                'created_at' => '2025-12-25 12:43:04',
                'updated_at' => '2026-01-03 15:49:04',
                'bot_mother_id' => 1,
                'endpoint_id' => 'webhook-personnel-admin',
                'language_code' => 'fa',
                'type' => 'telegram',
            ),
            8 => 
            array (
                'id' => 13,
                'telegram_owner_chat_id' => NULL,
                'telegram_bot_name' => NULL,
                'telegram_bot_token' => NULL,
                'telegram_get_me_api_response' => NULL,
                'telegram_bot_status' => 'DeActive',
                'telegram_webhook_is_set' => 0,
                'bale_owner_chat_id' => 6877922777,
                'bale_bot_name' => 'islamvoice_admin_bot',
                'bale_bot_token' => '1025533294:_DyoaAKMq36OFNLggwlyOA2fnlrOhC3l2jM',
                'bale_get_me_api_response' => '{"id":1025533294,"is_bot":true,"first_name":"islamvoice_admin_bot","last_name":"","username":"islamvoice_admin_bot"}',
                'bale_bot_status' => 'Active',
                'bale_webhook_is_set' => 1,
                'block_strategy' => 'block_first',
                'supported_message_types' => 'text',
                'supported_message_template' => 'https://',
                'created_at' => '2025-12-25 12:44:10',
                'updated_at' => '2026-01-03 15:43:22',
                'bot_mother_id' => 1,
                'endpoint_id' => 'webhook-personnel-admin',
                'language_code' => 'fa',
                'type' => 'bale',
            ),
            9 => 
            array (
                'id' => 14,
                'telegram_owner_chat_id' => 6877922777,
                'telegram_bot_name' => 'voiceofislam_media_bot',
                'telegram_bot_token' => '8289736795:AAE6CrLpVlzgCTmrpnkbSxt_pSmoYF4GZMc',
                'telegram_get_me_api_response' => '{"id":8289736795,"is_bot":true,"first_name":"\\u0631\\u0648\\u0628\\u0627\\u062a \\u0645\\u062f\\u06cc\\u0627\\u06cc \\u062a\\u0628\\u0644\\u06cc\\u063a","username":"voiceofislam_media_bot","can_join_groups":true,"can_read_all_group_messages":false,"supports_inline_queries":false,"can_connect_to_business":false,"has_main_web_app":false,"has_topics_enabled":false}',
                'telegram_bot_status' => 'Active',
                'telegram_webhook_is_set' => 1,
                'bale_owner_chat_id' => NULL,
                'bale_bot_name' => NULL,
                'bale_bot_token' => NULL,
                'bale_get_me_api_response' => NULL,
                'bale_bot_status' => 'DeActive',
                'bale_webhook_is_set' => 0,
                'block_strategy' => 'block_first',
                'supported_message_types' => 'text',
                'supported_message_template' => 'https://',
                'created_at' => '2025-12-25 14:41:35',
                'updated_at' => '2026-01-03 15:42:30',
                'bot_mother_id' => 1,
                'endpoint_id' => 'webhook-mission-media',
                'language_code' => 'fa',
                'type' => 'telegram',
            ),
            10 => 
            array (
                'id' => 15,
                'telegram_owner_chat_id' => NULL,
                'telegram_bot_name' => NULL,
                'telegram_bot_token' => NULL,
                'telegram_get_me_api_response' => NULL,
                'telegram_bot_status' => 'DeActive',
                'telegram_webhook_is_set' => 0,
                'bale_owner_chat_id' => 6877922777,
                'bale_bot_name' => 'voiceofislam_media_bot',
                'bale_bot_token' => '1975590901:snPxyIi_dTyi_3egbwio_bfPuA6uDiLdiho',
                'bale_get_me_api_response' => '{"id":1975590901,"is_bot":true,"first_name":"voiceofislam_media_bot","last_name":"","username":"voiceofislam_media_bot"}',
                'bale_bot_status' => 'Active',
                'bale_webhook_is_set' => 1,
                'block_strategy' => 'block_first',
                'supported_message_types' => 'text',
                'supported_message_template' => 'https://',
                'created_at' => '2025-12-25 15:06:07',
                'updated_at' => '2026-01-03 15:41:51',
                'bot_mother_id' => 1,
                'endpoint_id' => 'webhook-mission-media',
                'language_code' => 'fa',
                'type' => 'bale',
            ),
            11 => 
            array (
                'id' => 16,
                'telegram_owner_chat_id' => 6877922777,
                'telegram_bot_name' => 'KoranTextBot',
                'telegram_bot_token' => '8251055739:AAF7b4iLLD4YWfYo56WX3bxQaYwdSLbUe6U',
                'telegram_get_me_api_response' => '{"id":8251055739,"is_bot":true,"first_name":"KoranTextBot","username":"KoranTextBot","can_join_groups":true,"can_read_all_group_messages":false,"supports_inline_queries":false,"can_connect_to_business":false,"has_main_web_app":false,"has_topics_enabled":false}',
                'telegram_bot_status' => 'Active',
                'telegram_webhook_is_set' => 1,
                'bale_owner_chat_id' => NULL,
                'bale_bot_name' => NULL,
                'bale_bot_token' => NULL,
                'bale_get_me_api_response' => NULL,
                'bale_bot_status' => 'DeActive',
                'bale_webhook_is_set' => 0,
                'block_strategy' => 'block_first',
                'supported_message_types' => 'text',
                'supported_message_template' => 'https://',
                'created_at' => '2026-01-01 08:11:44',
                'updated_at' => '2026-01-03 15:40:57',
                'bot_mother_id' => 1,
                'endpoint_id' => 'webhook-quran-word',
                'language_code' => 'de-DE',
                'type' => 'telegram',
            ),
            12 => 
            array (
                'id' => 17,
                'telegram_owner_chat_id' => 6877922777,
                'telegram_bot_name' => 'Coran_Texte_bot',
                'telegram_bot_token' => '8461920478:AAEBd35lDCeciVI_Z5DSRLyyjfnZVsrOarM',
                'telegram_get_me_api_response' => '{"id":8461920478,"is_bot":true,"first_name":"Coran Texte bot","username":"Coran_Texte_bot","can_join_groups":true,"can_read_all_group_messages":false,"supports_inline_queries":false,"can_connect_to_business":false,"has_main_web_app":false,"has_topics_enabled":false}',
                'telegram_bot_status' => 'Active',
                'telegram_webhook_is_set' => 1,
                'bale_owner_chat_id' => NULL,
                'bale_bot_name' => NULL,
                'bale_bot_token' => NULL,
                'bale_get_me_api_response' => NULL,
                'bale_bot_status' => 'DeActive',
                'bale_webhook_is_set' => 0,
                'block_strategy' => 'block_first',
                'supported_message_types' => 'text',
                'supported_message_template' => 'https://',
                'created_at' => '2026-01-01 15:28:31',
                'updated_at' => '2026-01-03 15:40:23',
                'bot_mother_id' => 1,
                'endpoint_id' => 'webhook-quran-word',
                'language_code' => 'fr',
                'type' => 'telegram',
            ),
            13 => 
            array (
                'id' => 18,
                'telegram_owner_chat_id' => 6877922777,
                'telegram_bot_name' => 'Tilawat_Quran_Bot',
                'telegram_bot_token' => '8394424409:AAHEBKhfKyZPGElpfG4MRMqDG3A6KpqWXxA',
                'telegram_get_me_api_response' => '{"id":8394424409,"is_bot":true,"first_name":"Tilawat Quran Bot","username":"Tilawat_Quran_Bot","can_join_groups":true,"can_read_all_group_messages":false,"supports_inline_queries":false,"can_connect_to_business":false,"has_main_web_app":false,"has_topics_enabled":false}',
                'telegram_bot_status' => 'Active',
                'telegram_webhook_is_set' => 1,
                'bale_owner_chat_id' => NULL,
                'bale_bot_name' => NULL,
                'bale_bot_token' => NULL,
                'bale_get_me_api_response' => NULL,
                'bale_bot_status' => 'DeActive',
                'bale_webhook_is_set' => 0,
                'block_strategy' => 'block_first',
                'supported_message_types' => 'text',
                'supported_message_template' => 'https://',
                'created_at' => '2026-01-01 15:30:03',
                'updated_at' => '2026-01-03 15:39:50',
                'bot_mother_id' => 1,
                'endpoint_id' => 'webhook-quran-word',
                'language_code' => 'en',
                'type' => 'telegram',
            ),
            14 => 
            array (
                'id' => 19,
                'telegram_owner_chat_id' => 6877922777,
                'telegram_bot_name' => 'Koran_chteniye_bot',
                'telegram_bot_token' => '8474606220:AAGS_IizkiACKUgzHkeEp94U5Vz2zVhuf4U',
                'telegram_get_me_api_response' => '{"id":8474606220,"is_bot":true,"first_name":"Koran chteniye bot","username":"Koran_chteniye_bot","can_join_groups":true,"can_read_all_group_messages":false,"supports_inline_queries":false,"can_connect_to_business":false,"has_main_web_app":false,"has_topics_enabled":false}',
                'telegram_bot_status' => 'Active',
                'telegram_webhook_is_set' => 1,
                'bale_owner_chat_id' => NULL,
                'bale_bot_name' => NULL,
                'bale_bot_token' => NULL,
                'bale_get_me_api_response' => NULL,
                'bale_bot_status' => 'DeActive',
                'bale_webhook_is_set' => 0,
                'block_strategy' => 'block_first',
                'supported_message_types' => 'text',
                'supported_message_template' => 'https://',
                'created_at' => '2026-01-01 15:34:55',
                'updated_at' => '2026-01-03 15:38:51',
                'bot_mother_id' => 1,
                'endpoint_id' => 'webhook-quran-word',
                'language_code' => 'zh-CN',
                'type' => 'telegram',
            ),
            15 => 
            array (
                'id' => 20,
                'telegram_owner_chat_id' => 6877922777,
                'telegram_bot_name' => 'Kurani_Kerim_bot',
                'telegram_bot_token' => '8316690351:AAHEaCV8gOAoamfOEBIhZi9ulmBMpze5l50',
                'telegram_get_me_api_response' => '{"id":8316690351,"is_bot":true,"first_name":"Kurani Kerim bot","username":"Kurani_Kerim_bot","can_join_groups":true,"can_read_all_group_messages":false,"supports_inline_queries":false,"can_connect_to_business":false,"has_main_web_app":false,"has_topics_enabled":false}',
                'telegram_bot_status' => 'Active',
                'telegram_webhook_is_set' => 1,
                'bale_owner_chat_id' => NULL,
                'bale_bot_name' => NULL,
                'bale_bot_token' => NULL,
                'bale_get_me_api_response' => NULL,
                'bale_bot_status' => 'DeActive',
                'bale_webhook_is_set' => 0,
                'block_strategy' => 'block_first',
                'supported_message_types' => 'text',
                'supported_message_template' => 'https://',
                'created_at' => '2026-01-01 15:36:12',
                'updated_at' => '2026-01-03 15:37:40',
                'bot_mother_id' => 1,
                'endpoint_id' => 'webhook-quran-word',
                'language_code' => 'tr',
                'type' => 'telegram',
            ),
            16 => 
            array (
                'id' => 21,
                'telegram_owner_chat_id' => 6877922777,
                'telegram_bot_name' => 'mohaymen_robot',
                'telegram_bot_token' => '8337989357:AAGadK8qUGVBcVUTB7i9E_R4GTkKiQgnXLk',
                'telegram_get_me_api_response' => '{"id":8337989357,"is_bot":true,"first_name":"mohaymen","username":"mohaymen_robot","can_join_groups":true,"can_read_all_group_messages":false,"supports_inline_queries":false,"can_connect_to_business":false,"has_main_web_app":false,"has_topics_enabled":false}',
                'telegram_bot_status' => 'Active',
                'telegram_webhook_is_set' => 1,
                'bale_owner_chat_id' => NULL,
                'bale_bot_name' => NULL,
                'bale_bot_token' => NULL,
                'bale_get_me_api_response' => NULL,
                'bale_bot_status' => 'DeActive',
                'bale_webhook_is_set' => 0,
                'block_strategy' => 'block_first',
                'supported_message_types' => 'text',
                'supported_message_template' => 'https://',
                'created_at' => '2026-01-01 17:08:35',
                'updated_at' => '2026-01-03 15:36:49',
                'bot_mother_id' => 1,
                'endpoint_id' => 'webhook-presenter-bot',
                'language_code' => 'fa',
                'type' => 'telegram',
            ),
            17 => 
            array (
                'id' => 22,
                'telegram_owner_chat_id' => 6877922777,
                'telegram_bot_name' => 'Quraniarobot',
                'telegram_bot_token' => '6972155892:AAG50WuMxepv_8eAkcB5jArtTbL1mUH6vPs',
                'telegram_get_me_api_response' => '{"id":6972155892,"is_bot":true,"first_name":"Quraniarobot","username":"Quraniarobot","can_join_groups":true,"can_read_all_group_messages":false,"supports_inline_queries":false,"can_connect_to_business":false,"has_main_web_app":false,"has_topics_enabled":false}',
                'telegram_bot_status' => 'Active',
                'telegram_webhook_is_set' => 1,
                'bale_owner_chat_id' => NULL,
                'bale_bot_name' => NULL,
                'bale_bot_token' => NULL,
                'bale_get_me_api_response' => NULL,
                'bale_bot_status' => 'DeActive',
                'bale_webhook_is_set' => 0,
                'block_strategy' => 'block_first',
                'supported_message_types' => 'text',
                'supported_message_template' => 'https://',
                'created_at' => '2026-01-02 05:43:14',
                'updated_at' => '2026-01-03 15:34:37',
                'bot_mother_id' => 1,
                'endpoint_id' => 'webhook-quran-word',
                'language_code' => 'ar-IQ',
                'type' => 'telegram',
            ),
            18 => 
            array (
                'id' => 23,
                'telegram_owner_chat_id' => 6877922777,
                'telegram_bot_name' => 'mission_registration_bot',
                'telegram_bot_token' => '8509860899:AAGfC5G3oXPIgMKimdSoaRZm1f5QZ0nexoA',
                'telegram_get_me_api_response' => '{"id":8509860899,"is_bot":true,"first_name":"\\u062b\\u0628\\u062a \\u0646\\u0627\\u0645 \\u0637\\u0631\\u062d \\u062a\\u0628\\u0644\\u06cc\\u063a \\u0642\\u0631\\u0622\\u0646 \\u0627\\u0633\\u0644\\u0627\\u0645 \\u0628\\u0647 140 \\u0632\\u0628\\u0627\\u0646","username":"mission_registration_bot","can_join_groups":true,"can_read_all_group_messages":false,"supports_inline_queries":false,"can_connect_to_business":false,"has_main_web_app":false,"has_topics_enabled":false}',
                'telegram_bot_status' => 'Active',
                'telegram_webhook_is_set' => 1,
                'bale_owner_chat_id' => NULL,
                'bale_bot_name' => NULL,
                'bale_bot_token' => NULL,
                'bale_get_me_api_response' => NULL,
                'bale_bot_status' => 'DeActive',
                'bale_webhook_is_set' => 0,
                'block_strategy' => 'block_first',
                'supported_message_types' => 'text',
                'supported_message_template' => 'https://',
                'created_at' => '2026-01-03 04:41:19',
                'updated_at' => '2026-01-03 15:32:52',
                'bot_mother_id' => 1,
                'endpoint_id' => 'webhook-mission-bot',
                'language_code' => 'fa',
                'type' => 'telegram',
            ),
        ));
        
        
    }
}