<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class RssItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('rss_items')->delete();
        
        \DB::table('rss_items')->insert(array (
            0 => 
            array (
                'id' => 1,
                'title' => 'tooljet youtube',
                'description' => 'tooljet youtube',
                'url' => 'https://rss.app/feeds/ll4TPpRbXPdRqvSx.xml',
                'url_ifttt' => NULL,
                'url_rss_dot_app' => 'https://rss.app/feeds/4fbMLZP15RoXxPSP.xml',
                'is_active' => 1,
                'unique_xml_tag' => NULL,
                'locale' => 'en',
                'target_locale' => 'fa',
                'rss_channel_id' => 1,
                'created_at' => '2024-06-02 20:54:16',
                'updated_at' => '2024-06-10 07:14:03',
                'rss_business_id' => 2,
            ),
            1 => 
            array (
                'id' => 2,
                'title' => 'saber blog',
                'description' => 'saber blog',
                'url' => 'http://127.0.0.1:8001/comments/feed/32',
                'url_ifttt' => NULL,
                'url_rss_dot_app' => NULL,
                'is_active' => 0,
                'unique_xml_tag' => 'guid',
                'locale' => 'fa',
                'target_locale' => 'fa',
                'rss_channel_id' => 1,
                'created_at' => '2024-06-02 20:54:16',
                'updated_at' => '2024-06-10 07:14:03',
                'rss_business_id' => 2,
            ),
            2 => 
            array (
                'id' => 3,
                'title' => 'saber blog post',
                'description' => 'saber blog post',
                'url' => 'http://127.0.0.1:8001/posts/feed/32',
                'url_ifttt' => NULL,
                'url_rss_dot_app' => NULL,
                'is_active' => 0,
                'unique_xml_tag' => 'guid',
                'locale' => 'fa',
                'target_locale' => 'fa',
                'rss_channel_id' => 1,
                'created_at' => '2024-06-02 20:54:16',
                'updated_at' => '2024-06-10 07:14:03',
                'rss_business_id' => 2,
            ),
            3 => 
            array (
                'id' => 4,
                'title' => 'saber blog virgool',
                'description' => 'saber blog virgool',
                'url' => 'https://virgool.io/feed/@saber.tabatabaee',
                'url_ifttt' => NULL,
                'url_rss_dot_app' => NULL,
                'is_active' => 0,
                'unique_xml_tag' => 'link',
                'locale' => 'fa',
                'target_locale' => 'fa',
                'rss_channel_id' => 1,
                'created_at' => '2024-06-02 20:54:16',
                'updated_at' => '2024-06-10 07:14:03',
                'rss_business_id' => 2,
            ),
            4 => 
            array (
                'id' => 5,
                'title' => 'Flowable | LinkedIn',
                'description' => 'Flowable | LinkedIn',
                'url' => 'https://rss.app/feeds/OlCBlCZgkAK9LJ1N.xml',
                'url_ifttt' => NULL,
                'url_rss_dot_app' => 'https://www.linkedin.com/company/flowable-group/',
                'is_active' => 0,
                'unique_xml_tag' => NULL,
                'locale' => 'en',
                'target_locale' => 'fa',
                'rss_channel_id' => 1,
                'created_at' => '2024-06-02 20:54:16',
                'updated_at' => '2024-06-10 07:14:03',
                'rss_business_id' => 1,
            ),
            5 => 
            array (
                'id' => 6,
                'title' => 'Camunda | LinkedIn',
                'description' => 'Camunda | LinkedIn',
                'url' => 'https://rss.app/feeds/V0RE23p2iiJ7hQ9c.xml',
                'url_ifttt' => NULL,
                'url_rss_dot_app' => NULL,
                'is_active' => 1,
                'unique_xml_tag' => NULL,
                'locale' => 'en',
                'target_locale' => 'fa',
                'rss_channel_id' => 1,
                'created_at' => '2024-06-10 06:54:51',
                'updated_at' => '2024-06-10 06:54:51',
                'rss_business_id' => 1,
            ),
            6 => 
            array (
                'id' => 7,
                'title' => 'Bizagi | LinkedIn',
                'description' => 'Bizagi | LinkedIn',
                'url' => 'https://rss.app/feeds/bZwm4uvDm2D98F2v.xml',
                'url_ifttt' => NULL,
                'url_rss_dot_app' => NULL,
                'is_active' => 1,
                'unique_xml_tag' => NULL,
                'locale' => 'en',
                'target_locale' => 'fa',
                'rss_channel_id' => 1,
                'created_at' => '2024-06-10 06:54:26',
                'updated_at' => '2024-06-10 06:54:26',
                'rss_business_id' => 1,
            ),
            7 => 
            array (
                'id' => 8,
                'title' => 'ProcessMaker | LinkedIn',
                'description' => 'ProcessMaker | LinkedIn',
                'url' => 'https://rss.app/feeds/zmMt3LJUphX8tTGw.xml',
                'url_ifttt' => NULL,
                'url_rss_dot_app' => NULL,
                'is_active' => 0,
                'unique_xml_tag' => NULL,
                'locale' => 'en',
                'target_locale' => 'fa',
                'rss_channel_id' => 1,
                'created_at' => '2024-06-06 05:26:45',
                'updated_at' => '2024-06-06 05:26:45',
                'rss_business_id' => 1,
            ),
            8 => 
            array (
                'id' => 9,
                'title' => 'camunda blog',
                'description' => 'camunda blog',
                'url' => 'https://camunda.com/blog/feed',
                'url_ifttt' => NULL,
                'url_rss_dot_app' => NULL,
                'is_active' => 1,
                'unique_xml_tag' => NULL,
                'locale' => 'en',
                'target_locale' => 'fa',
                'rss_channel_id' => 1,
                'created_at' => '2024-06-06 17:24:31',
                'updated_at' => '2024-06-06 17:24:31',
                'rss_business_id' => 1,
            ),
            9 => 
            array (
                'id' => 10,
                'title' => 'camunda youtube',
                'description' => 'camunda youtube',
                'url' => 'https://rss.app/feeds/j2ibxJn2k0omGYke.xml',
                'url_ifttt' => 'https://www.youtube.com/@CamundaTeam',
                'url_rss_dot_app' => 'https://rss.app/feeds/aVpVRnngVXvjZOjT.xml',
                'is_active' => 1,
                'unique_xml_tag' => NULL,
                'locale' => 'en',
                'target_locale' => 'fa',
                'rss_channel_id' => 1,
                'created_at' => '2024-06-10 06:54:04',
                'updated_at' => '2024-06-10 06:54:04',
                'rss_business_id' => 1,
            ),
            10 => 
            array (
                'id' => 11,
                'title' => 'camunda twitter',
                'description' => 'camunda twitter',
                'url' => 'https://rss.app/feeds/Her2n9iEl9fvayxU.xml',
                'url_ifttt' => NULL,
                'url_rss_dot_app' => NULL,
                'is_active' => 0,
                'unique_xml_tag' => NULL,
                'locale' => 'en',
                'target_locale' => 'fa',
                'rss_channel_id' => 1,
                'created_at' => '2024-06-06 19:40:25',
                'updated_at' => '2024-06-06 19:40:25',
                'rss_business_id' => 1,
            ),
            11 => 
            array (
                'id' => 12,
                'title' => 'flowable blog',
                'description' => 'flowable blog',
                'url' => 'https://flowable.com/blog/feed',
                'url_ifttt' => NULL,
                'url_rss_dot_app' => NULL,
                'is_active' => 0,
                'unique_xml_tag' => NULL,
                'locale' => 'en',
                'target_locale' => 'fa',
                'rss_channel_id' => 1,
                'created_at' => '2024-06-06 17:33:26',
                'updated_at' => '2024-06-06 17:33:26',
                'rss_business_id' => 1,
            ),
            12 => 
            array (
                'id' => 13,
                'title' => 'flowable linkedin',
                'description' => 'flowable linkedin',
                'url' => 'https://rss.app/feeds/I6FOYm9cGUQfiU4T.xml',
                'url_ifttt' => NULL,
                'url_rss_dot_app' => NULL,
                'is_active' => 1,
                'unique_xml_tag' => NULL,
                'locale' => 'en',
                'target_locale' => 'fa',
                'rss_channel_id' => 1,
                'created_at' => '2024-06-10 06:58:29',
                'updated_at' => '2024-06-10 06:58:29',
                'rss_business_id' => 1,
            ),
            13 => 
            array (
                'id' => 14,
                'title' => 'flowable youtube',
                'description' => 'flowable youtube',
                'url' => 'https://rss.app/feeds/VLncU0ntuu5kpxA4.xml',
                'url_ifttt' => NULL,
                'url_rss_dot_app' => NULL,
                'is_active' => 1,
                'unique_xml_tag' => NULL,
                'locale' => 'en',
                'target_locale' => 'fa',
                'rss_channel_id' => 1,
                'created_at' => '2024-06-10 06:58:04',
                'updated_at' => '2024-06-10 06:58:04',
                'rss_business_id' => 1,
            ),
            14 => 
            array (
                'id' => 15,
                'title' => 'flowable twitter',
                'description' => 'flowable twitter',
                'url' => 'https://rss.app/feeds/KRwQwndmsC9q4cSo.xml',
                'url_ifttt' => NULL,
                'url_rss_dot_app' => NULL,
                'is_active' => 0,
                'unique_xml_tag' => NULL,
                'locale' => 'en',
                'target_locale' => 'fa',
                'rss_channel_id' => 1,
                'created_at' => '2024-06-06 19:40:36',
                'updated_at' => '2024-06-06 19:40:36',
                'rss_business_id' => 1,
            ),
            15 => 
            array (
                'id' => 16,
                'title' => 'process_maker blog',
                'description' => 'process_maker blog',
                'url' => 'https://www.processmaker.com/blog/feed',
                'url_ifttt' => NULL,
                'url_rss_dot_app' => NULL,
                'is_active' => 1,
                'unique_xml_tag' => NULL,
                'locale' => 'en',
                'target_locale' => 'fa',
                'rss_channel_id' => 1,
                'created_at' => '2024-06-06 17:33:54',
                'updated_at' => '2024-06-06 17:33:54',
                'rss_business_id' => 1,
            ),
            16 => 
            array (
                'id' => 17,
                'title' => 'process_maker facebook',
                'description' => 'process_maker facebook',
                'url' => 'https://www.facebook.com/processmaker',
                'url_ifttt' => NULL,
                'url_rss_dot_app' => NULL,
                'is_active' => 0,
                'unique_xml_tag' => NULL,
                'locale' => 'en',
                'target_locale' => 'fa',
                'rss_channel_id' => 1,
                'created_at' => '2024-06-07 14:41:59',
                'updated_at' => '2024-06-07 14:41:59',
                'rss_business_id' => 1,
            ),
            17 => 
            array (
                'id' => 18,
                'title' => 'process_maker linkedin',
                'description' => 'process_maker linkedin',
                'url' => 'https://rss.app/feeds/oMSPuNGOxaZ6JPvV.xml',
                'url_ifttt' => NULL,
                'url_rss_dot_app' => NULL,
                'is_active' => 1,
                'unique_xml_tag' => NULL,
                'locale' => 'en',
                'target_locale' => 'fa',
                'rss_channel_id' => 1,
                'created_at' => '2024-06-10 06:53:40',
                'updated_at' => '2024-06-10 06:53:40',
                'rss_business_id' => 1,
            ),
            18 => 
            array (
                'id' => 19,
                'title' => 'process_maker youtube',
                'description' => 'process_maker youtube',
                'url' => 'https://rss.app/feeds/jSgYnLYxinm7DeaM.xml',
                'url_ifttt' => NULL,
                'url_rss_dot_app' => NULL,
                'is_active' => 1,
                'unique_xml_tag' => NULL,
                'locale' => 'en',
                'target_locale' => 'fa',
                'rss_channel_id' => 1,
                'created_at' => '2024-06-10 06:53:19',
                'updated_at' => '2024-06-10 06:53:19',
                'rss_business_id' => 1,
            ),
            19 => 
            array (
                'id' => 20,
                'title' => 'stackoverflow flowable',
                'description' => NULL,
                'url' => 'https://stackoverflow.com/feeds/tag?tagnames=flowable&sort=votes',
                'url_ifttt' => NULL,
                'url_rss_dot_app' => NULL,
                'is_active' => 0,
                'unique_xml_tag' => NULL,
                'locale' => 'en',
                'target_locale' => 'fa',
                'rss_channel_id' => 1,
                'created_at' => '2024-06-11 06:44:04',
                'updated_at' => '2024-06-11 06:44:04',
                'rss_business_id' => 1,
            ),
        ));
        
        
    }
}