<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class SharabeBeheshtiMp3sTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('sharabe_beheshti_mp3s')->delete();
        
        \DB::table('sharabe_beheshti_mp3s')->insert(array (
            0 => 
            array (
                'id' => 1,
                'title' => 'نهج البلاغه – خطبه 165',
                'description' => '-',
                'part_name' => 'نهج البلاغه',
                'part' => '1',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/1/01_Nahj_al_Balaghe_Khotbe_165.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'title' => 'مقدمه',
                'description' => '-',
                'part_name' => 'نهج البلاغه',
                'part' => '1',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/1/02_Nahj_al_Balaghe_Moghaddame.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'title' => 'نهج البلاغه – خطبه 183',
                'description' => '-',
                'part_name' => 'نهج البلاغه',
                'part' => '1',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/1/03_Nahj_al_Balaghe_Khotbe_183.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'title' => 'نهج البلاغه – خطبه 197',
                'description' => '-',
                'part_name' => 'نهج البلاغه',
                'part' => '1',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/1/04_Nahj_al_Balaghe_Khotbe_197.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'title' => 'نهج البلاغه – خطبه 26',
                'description' => '-',
                'part_name' => 'نهج البلاغه',
                'part' => '1',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/1/05_Nahj_al_Balaghe_Khotbe_26.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'title' => 'نهج البلاغه – خطبه 207',
                'description' => '-',
                'part_name' => 'نهج البلاغه',
                'part' => '1',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/1/06_Nahj_al_Balaghe_Khotbe_207.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'title' => 'نهج البلاغه – نامه 14',
                'description' => '-',
                'part_name' => 'نهج البلاغه',
                'part' => '1',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/1/07_Nahj_al_Balaghe_Naame_14.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'title' => 'نهج البلاغه – نامه 10',
                'description' => '-',
                'part_name' => 'نهج البلاغه',
                'part' => '1',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/1/08_Nahj_al_Balaghe_Naame_10.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'title' => 'نهج البلاغه – خطبه 182',
                'description' => '-',
                'part_name' => 'نهج البلاغه',
                'part' => '1',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/1/09_Nahj_al_Balaghe_Khotbe_182.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'title' => 'نهج البلاغه – نامه 47',
                'description' => '-',
                'part_name' => 'نهج البلاغه',
                'part' => '1',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/1/10_Nahj_al_Balaghe_Naame_47.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'title' => 'نهج البلاغه – خطبه 125',
                'description' => '-',
                'part_name' => 'نهج البلاغه',
                'part' => '1',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/1/11_Nahj_al_Balaghe_Khotbe_125.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'title' => 'نهج البلاغه – خطبه 161',
                'description' => '-',
                'part_name' => 'نهج البلاغه',
                'part' => '1',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/1/12_Nahj_al_Balaghe_Khotbe_161.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'title' => 'نهج البلاغه – خطبه 138',
                'description' => '-',
                'part_name' => 'نهج البلاغه',
                'part' => '1',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/1/13_Nahj_al_Balaghe_Khotbe_138.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'title' => 'نهج البلاغه – خطبه 199',
                'description' => '-',
                'part_name' => 'نهج البلاغه',
                'part' => '1',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/1/14_Nahj_al_Balaghe_Khotbe_199.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'title' => 'نهج البلاغه – خطبه 203',
                'description' => '-',
                'part_name' => 'نهج البلاغه',
                'part' => '1',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/1/16_Nahj_al_Balaghe_Khotbe_203.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'title' => 'نهج البلاغه – خطبه 207',
                'description' => '-',
                'part_name' => 'نهج البلاغه',
                'part' => '1',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/1/06_Nahj_al_Balaghe_Khotbe_207.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'title' => 'نهج البلاغه – خطبه 2',
                'description' => '-',
                'part_name' => 'نهج البلاغه',
                'part' => '1',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/1/76_Nahj_al_Balaghe_Khotbe_2.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'title' => 'نهج البلاغه – خطبه 3',
                'description' => '-',
                'part_name' => 'نهج البلاغه',
                'part' => '1',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/1/88_Nahj_al_Balaghe_Khotbe_3.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'title' => 'نهج البلاغه – حکمت 372',
                'description' => '-',
                'part_name' => 'نهج البلاغه',
                'part' => '1',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/1/58_Nahj_al_Balaghe_Hekmat_372.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'title' => 'مقدمه',
                'description' => '-',
                'part_name' => 'صحیفه سجادیه',
                'part' => '2',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/2/01_Sahifeh_Sajjadieh_Moghaddame.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'title' => 'دعای 1 – ستایش خداوند عزوجل',
                'description' => '-',
                'part_name' => 'صحیفه سجادیه',
                'part' => '2',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/2/02_Sahifeh_Sajjadieh_Doa_1.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'title' => 'دعای 20 – نیایش آن حضرت در طلب خوی‌های نیک',
                'description' => '-',
                'part_name' => 'صحیفه سجادیه',
                'part' => '2',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/2/03_Sahifeh_Sajjadieh_Doa_20.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'title' => 'دعای 12 – نیایش آن حضرت در اعتراف به گناه',
                'description' => '-',
                'part_name' => 'صحیفه سجادیه',
                'part' => '2',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/2/04_Sahifeh_Sajjadieh_Doa_12.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'title' => 'دعای 39 – نیایش آن حضرت در طلب عفو و بخشایش',
                'description' => '-',
                'part_name' => 'صحیفه سجادیه',
                'part' => '2',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/2/05_Sahifeh_Sajjadieh_Doa_39.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'title' => 'دعای 15 – نیایش آن حضرت در پناه بردن به خدا',
                'description' => '-',
                'part_name' => 'صحیفه سجادیه',
                'part' => '2',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/2/06_Sahifeh_Sajjadieh_Doa_15.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'title' => 'دعای 47 – نیایش آن حضرت در روز عرفه',
                'description' => '-',
                'part_name' => 'صحیفه سجادیه',
                'part' => '2',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/2/07_Sahifeh_Sajjadieh_Doa_47.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'title' => 'دعای 17 – نیایش آن حضرت در نفرین بر شیطان',
                'description' => '-',
                'part_name' => 'صحیفه سجادیه',
                'part' => '2',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/2/08_Sahifeh_Sajjadieh_Doa_17.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'title' => 'دعای 41 – نیایش آن حضرت در طلب پرده پوشی',
                'description' => '-',
                'part_name' => 'صحیفه سجادیه',
                'part' => '2',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/2/09_Sahifeh_Sajjadieh_Doa_41.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'title' => 'دعای 22 – نیایش آن حضرت در هنگام سختی',
                'description' => '-',
                'part_name' => 'صحیفه سجادیه',
                'part' => '2',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/2/10_Sahifeh_Sajjadieh_Doa_22.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'title' => 'دعای 31 – نیایش آن حضرت درباره توبه',
                'description' => '-',
                'part_name' => 'صحیفه سجادیه',
                'part' => '2',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/2/20_Sahifeh_Sajjadieh_Doa_31.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'title' => 'دعای 3 – صلوات و درود بر حاملان عرش الهی',
                'description' => '-',
                'part_name' => 'صحیفه سجادیه',
                'part' => '2',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/2/21_Sahifeh_Sajjadieh_Doa_3.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'title' => 'دعای 37 – نیایش آن حضرت در طلب شکر پروردگار',
                'description' => '-',
                'part_name' => 'صحیفه سجادیه',
                'part' => '2',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/2/22_Sahifeh_Sajjadieh_Doa_37.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'title' => 'قرآن کریم – سوره مبارکه واقعه',
                'description' => '-',
                'part_name' => 'قرآن',
                'part' => '3',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/3/01_Vaghee.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'title' => 'مقدمه',
                'description' => '-',
                'part_name' => 'قرآن',
                'part' => '3',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/3/02_ Moghaddame.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'title' => 'قرآن کریم – سوره مبارکه نبا',
                'description' => '-',
                'part_name' => 'قرآن',
                'part' => '3',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/3/03_Naba.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'title' => 'قرآن کریم – سوره مبارکه ذاریات',
                'description' => '-',
                'part_name' => 'قرآن',
                'part' => '3',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/3/04_Zariat.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'title' => 'قرآن کریم – سوره مبارکه غاشیه',
                'description' => '-',
                'part_name' => 'قرآن',
                'part' => '3',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/3/05_Ghashie.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'title' => 'قرآن کریم – سوره مبارکه بلد',
                'description' => '-',
                'part_name' => 'قرآن',
                'part' => '3',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/3/06_Balad.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
            'title' => 'قرآن کریم – سوره مبارکه ق (قاف)',
                'description' => '-',
                'part_name' => 'قرآن',
                'part' => '3',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/3/07_Ghaf.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
            'title' => 'قرآن کریم – سوره مبارکه رحمان (الرحمان)',
                'description' => '-',
                'part_name' => 'قرآن',
                'part' => '3',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/3/08_Alrahman.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'title' => 'قرآن کریم – سوره مبارکه انسان',
                'description' => '-',
                'part_name' => 'قرآن',
                'part' => '3',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/3/09_Ensan.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'title' => 'قرآن کریم – سوره مبارکه صف',
                'description' => '-',
                'part_name' => 'قرآن',
                'part' => '3',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/3/10_Saf.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'title' => 'قرآن کریم – سوره مبارکه طور',
                'description' => '-',
                'part_name' => 'قرآن',
                'part' => '3',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/3/11_Toor.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'title' => 'قرآن کریم – سوره مبارکه مزمل',
                'description' => '-',
                'part_name' => 'قرآن',
                'part' => '3',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/3/12_Mozzammel.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'title' => 'قرآن کریم – سوره مبارکه مطففین',
                'description' => '-',
                'part_name' => 'قرآن',
                'part' => '3',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/3/13_Motaffefin.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'title' => 'قرآن کریم – سوره مبارکه معارج',
                'description' => '-',
                'part_name' => 'قرآن',
                'part' => '3',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/3/14_Maarej.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'title' => 'قرآن کریم – سوره مبارکه محمد',
                'description' => '-',
                'part_name' => 'قرآن',
                'part' => '3',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/3/15_Mohammad.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'title' => 'قرآن کریم – سوره مبارکه ابراهیم',
                'description' => '-',
                'part_name' => 'قرآن',
                'part' => '3',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/3/16_Ebrahim.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'title' => 'قرآن کریم – سوره مبارکه یاسین',
                'description' => '-',
                'part_name' => 'قرآن',
                'part' => '3',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/3/17_Yasin.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'title' => 'قرآن کریم – سوره مبارکه لقمان',
                'description' => '-',
                'part_name' => 'قرآن',
                'part' => '3',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/3/18_Loghman.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'title' => 'قرآن کریم – سوره مبارکه تکویر',
                'description' => '-',
                'part_name' => 'قرآن',
                'part' => '3',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/3/19_Takvir.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'title' => 'قرآن کریم – سوره مبارکه حاقه',
                'description' => '-',
                'part_name' => 'قرآن',
                'part' => '3',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/3/20_Haghe.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'title' => 'زیارت عاشورا – افزوده شده در آبان 1401',
                'description' => '-',
                'part_name' => 'مفاتیج الجنان',
                'part' => '4',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/4/Ziyarat_Ashoora.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'title' => 'زیارت آل یاسین',
                'description' => '-',
                'part_name' => 'مفاتیج الجنان',
                'part' => '4',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/4/AleYasin.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
            'title' => 'دعای امام حسین (ع) در روز عرفه',
                'description' => '-',
                'part_name' => 'مفاتیج الجنان',
                'part' => '4',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/4/Arafe.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'title' => 'زیارت جامعه‌کبیره',
                'description' => '-',
                'part_name' => 'مفاتیج الجنان',
                'part' => '4',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/4/Jamee.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'title' => 'دعای کمیل',
                'description' => '-',
                'part_name' => 'مفاتیج الجنان',
                'part' => '4',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/4/Komeil.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'title' => 'دعای ندبه',
                'description' => '-',
                'part_name' => 'مفاتیج الجنان',
                'part' => '4',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/4/Nodbe.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
            'title' => 'زیارت امیرالمومنین علی(ع) در روز غدیر',
                'description' => '-',
                'part_name' => 'مفاتیج الجنان',
                'part' => '4',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/4/ghadir.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'title' => 'قرآن کریم – سوره مبارکه رعد آیه 31',
                'description' => '-',
                'part_name' => 'قرآن',
                'part' => '5',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/5/01_Quran_Raad_31.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'title' => 'قرآن کریم – سوره مبارکه حشر آیه 18 الی 24',
                'description' => '-',
                'part_name' => 'قرآن',
                'part' => '5',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/5/02_Quran_Hashr_18_24.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'title' => 'قرآن کریم – سوره مبارکه فجر',
                'description' => '-',
                'part_name' => 'قرآن',
                'part' => '5',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/5/03_Quran_Fajr.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'title' => 'قرآن کریم – سوره مبارکه حجر آیه 23 الی 48',
                'description' => '-',
                'part_name' => 'قرآن',
                'part' => '5',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/5/04_Quran_Hejr_23_48.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'title' => 'قرآن کریم – سوره مبارکه فرقان آیه 20 الی 36',
                'description' => '-',
                'part_name' => 'قرآن',
                'part' => '5',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/5/05_Quran_Forghan_20_36.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            64 => 
            array (
                'id' => 65,
            'title' => 'قرآن کریم – سوره مبارکه طه (طاها)',
                'description' => '-',
                'part_name' => 'قرآن',
                'part' => '5',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/5/06_Quran_Taha.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'title' => 'قرآن کریم – سوره مبارکه نمل آیه 1 الی 44',
                'description' => '-',
                'part_name' => 'قرآن',
                'part' => '5',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/5/07_Quran_Naml_1_44.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            66 => 
            array (
                'id' => 67,
                'title' => 'قرآن کریم – سوره مبارکه شورا آیه 22 الی 38',
                'description' => '-',
                'part_name' => 'قرآن',
                'part' => '5',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/5/08_Quran_Shora_22_38.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'title' => 'قرآن کریم – سوره مبارکه حدید آیه 20 الی 24',
                'description' => '-',
                'part_name' => 'قرآن',
                'part' => '5',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/5/09_Quran_Hadid_20_24.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            68 => 
            array (
                'id' => 69,
                'title' => 'قرآن کریم – سوره مبارکه رعد آیه 20 الی 26',
                'description' => '-',
                'part_name' => 'قرآن',
                'part' => '5',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/5/10_Quran_Raad_20_26.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            69 => 
            array (
                'id' => 70,
                'title' => 'قرآن کریم – سوره مبارکه هود آیه 84 الی 95',
                'description' => '-',
                'part_name' => 'قرآن',
                'part' => '5',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/5/11_Quran_Hood_84_95.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            70 => 
            array (
                'id' => 71,
                'title' => 'قرآن کریم – سوره مبارکه ملک',
                'description' => '-',
                'part_name' => 'قرآن',
                'part' => '5',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/5/12_Quran_Molk.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            71 => 
            array (
                'id' => 72,
                'title' => 'قرآن کریم – سوره مبارکه مائده آیه 51 الی 59',
                'description' => '-',
                'part_name' => 'قرآن',
                'part' => '5',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/5/13_Quran_Maede_51_59.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            72 => 
            array (
                'id' => 73,
                'title' => 'قرآن کریم – سوره مبارکه صافات آیه 1 الی 68',
                'description' => '-',
                'part_name' => 'قرآن',
                'part' => '5',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/5/14_Quran_Saffat_1_68.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            73 => 
            array (
                'id' => 74,
                'title' => 'قرآن کریم – سوره مبارکه اعراف آیه 1 الی 29',
                'description' => '-',
                'part_name' => 'قرآن',
                'part' => '5',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/5/15_Quran_Aaraf_1_29.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            74 => 
            array (
                'id' => 75,
                'title' => 'قرآن کریم – سوره مبارکه آل عمران آیه 45 الی 63',
                'description' => '-',
                'part_name' => 'قرآن',
                'part' => '5',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/5/16_Quran_Ale_emran_45_63.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            75 => 
            array (
                'id' => 76,
                'title' => 'قرآن کریم – سوره مبارکه قمر',
                'description' => '-',
                'part_name' => 'قرآن',
                'part' => '5',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/5/17_Quran_Ghamar.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            76 => 
            array (
                'id' => 77,
                'title' => 'قرآن کریم – سوره مبارکه لیل',
                'description' => '-',
                'part_name' => 'قرآن',
                'part' => '5',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/5/18_Quran_lail.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            77 => 
            array (
                'id' => 78,
                'title' => 'قرآن کریم – سوره مبارکه مرسلات',
                'description' => '-',
                'part_name' => 'قرآن',
                'part' => '5',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/5/19_Quran_Morsalat.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            78 => 
            array (
                'id' => 79,
                'title' => 'قرآن کریم – سوره مبارکه بینه',
                'description' => '-',
                'part_name' => 'قرآن',
                'part' => '5',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/5/20_Quran_Bayyene.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            79 => 
            array (
                'id' => 80,
                'title' => 'قرآن کریم – سوره مبارکه اعراف آیه 40 الی 45',
                'description' => '-',
                'part_name' => 'قرآن',
                'part' => '5',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/5/21_Quran_Aaraf_40_45.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            80 => 
            array (
                'id' => 81,
                'title' => 'قرآن کریم – سوره مبارکه فرقان آیه 61 الی 77',
                'description' => '-',
                'part_name' => 'قرآن',
                'part' => '5',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/5/22_Quran_Forghan_61_77.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            81 => 
            array (
                'id' => 82,
                'title' => 'قرآن کریم – سوره مبارکه قلم',
                'description' => '-',
                'part_name' => 'قرآن',
                'part' => '5',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/5/23_Quran_Ghalam.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            82 => 
            array (
                'id' => 83,
                'title' => 'قرآن کریم – سوره مبارکه فاطر آیه 1 الی 37',
                'description' => '-',
                'part_name' => 'قرآن',
                'part' => '5',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/5/24_Quran_Fater_1_37.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            83 => 
            array (
                'id' => 84,
                'title' => 'قرآن کریم – سوره مبارکه انبیا آیه 1 الی 23',
                'description' => '-',
                'part_name' => 'قرآن',
                'part' => '5',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/5/25_Quran_Anbia_1_23.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            84 => 
            array (
                'id' => 85,
                'title' => 'قرآن کریم – سوره مبارکه زمر آیه 45 الی 75',
                'description' => '-',
                'part_name' => 'قرآن',
                'part' => '5',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/5/31_Quran_Zomar_45_75.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            85 => 
            array (
                'id' => 86,
                'title' => 'قرآن کریم – سوره مبارکه ماعون',
                'description' => '-',
                'part_name' => 'قرآن',
                'part' => '5',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/5/32_Qura_Maoon.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            86 => 
            array (
                'id' => 87,
                'title' => 'قرآن کریم – سوره مبارکه علق',
                'description' => '-',
                'part_name' => 'قرآن',
                'part' => '5',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/5/33_Quran_Alagh.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            87 => 
            array (
                'id' => 88,
            'title' => 'قرآن کریم – سوره مبارکه بقره آیه 255 الی 257 (آیة الکرسی)',
                'description' => '-',
                'part_name' => 'قرآن',
                'part' => '5',
                'origin' => 'sharabebeheshti.ir',
                'link' => 'https://dl.anibeen.com/sharabebeheshti/5/34_Quran_Ayat_al_Korsi.mp3',
                'details' => '{}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}